### PR TITLE
v221

### PR DESCRIPTION
**Pull request by rboykin**
Bump cf-release to v221
Add route_registrar job
Add uaa.proxy.servers
Change gorouter client authorities
Add cc_routing client
Change etcd to not require ssl
Add loggregator.etcd.machines
Add route_registrar.routes

### CODE REVIEW

**Comment by yudai** [comment]
Thank you for the PR. Right now I have no time to validate your work. Will do something next week.

**Comment by rboykin** [comment]
Thanks @yudai.  In a local environment without checking-in, I have also been able to point to v222 and these changes also work for that release.

**Comment by rboykin** [comment]
In a local environment without checking-in, I have also been able to point to v223 and these changes also work for that release.

**Comment by rboykin** [comment]
@yudai, any movement on accepting this PR?

**Comment by yudai** [comment]
@rboykin Sorry for the late reply. I confirmed your PR works perfectly.
Thank you very much.

I'll test with v223 soon.

**Comment by rboykin** [comment]
@yudai Thanks for the merge.  And thanks so much for providing cf_nise_installer.  It makes developing and testing with a local installation of Cloud Foundry incredibly easy.

**Pull request merged**
